language: python
python:
- '3.6'
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: jsbroks
  on:
    tags: true
  password:
    secure: w2e8oO5xdAHW7F3I+z/rVV2yb9EiRVryKpx0B3W80/CmyFRKqb5yIJ2mGlnLcStKYb0ayatdIQcaFg1lFpNy2QtXH1LxhG7SNI0/JFIqIJxcAo17pU+6QO2h3KnZkdLuZtXM8OmuSqiFBtcqC/PpoS7xFqExodsbj8BZyJSuiDIthfBoWveFfY6i1km5hps0SnBfwROAfWqb3PDY1dEiwLIIpHe47rwhsy1EAVXKN8XtIhDznEuoP49h5uIw0BO51W/4GGPMw+gM1LHEHjI5mJgSEp/2kqJP8liHgBGjc2R8EDwIcGMOUFnpahG+f92rUOfk6EDbnWmTb7V0nDvcWRYl+pFxVYYp/qrgbTTrRw+6Dlvp4rIkyRpfvgFhoFu9oC1VCQSJstWuoC0HJbAzw01+/P8Gd7psZKyCtm+I3Rnm+xt9aYrVKdj5YSrWqa0FzH4vlxGwNitkmVYbi0TGltfq9ObsOAtaLgAxwE2zv7/d1kgp/eGZMYCDSRBTc8QIxKzxmJXUP2k4ISFB7u5qaeTWabWEipHxYwPToF+XL1m0wymHfS2XyzJ1XQY69MCSPCG6V+ciKS0oH2UBoR2qk+frkG7NJ7MC1q7M2UHdHFwn1lqM7dkxVlKQJTqfz4v+jIKgLX/9jDUUVtWyMl56/6GMqC6bRGMnfGkN0SSaXRc=
